{"name": "Получение ошибки данных о несуществующем заказе", "status": "passed", "description": "Проверка получения данных о заказе с несуществующим номером | GET /api/v1/orders/track", "start": 1716550350145, "stop": 1716550350270, "uuid": "13ede832-f829-4bac-a622-242a692545b0", "historyId": "0ea258dd7f709de303ed40d2bb064464", "testCaseId": "0ea258dd7f709de303ed40d2bb064464", "fullName": "test_create_order.TestTrackingOrder#test_order_track_bad_order_failed", "labels": [{"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestTrackingOrder"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "11044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_order"}]}