{"name": "Получение ошибки данных о заказе без номера", "status": "passed", "description": "Проверка получения данных о заказе без номера | GET /api/v1/orders/track", "start": 1716550349957, "stop": 1716550350145, "uuid": "c265eb70-1853-4c0a-8236-0d663318a621", "historyId": "f67b719de9cac953f7fa7b82302da2c5", "testCaseId": "f67b719de9cac953f7fa7b82302da2c5", "fullName": "test_create_order.TestTrackingOrder#test_order_track_no_order_id_failed", "labels": [{"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestTrackingOrder"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "11044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_order"}]}