{"name": "Получение ошибки приема заказа с некорректным id курьера", "status": "passed", "description": "Проверка принятия заказа с неверным id курьера | GET /api/v1/orders/track", "start": 1716550352426, "stop": 1716550352941, "uuid": "11f057ea-6353-4b44-b6ff-c1510a119f83", "historyId": "a519fa134e120f46ad2f8fc378caa990", "testCaseId": "a519fa134e120f46ad2f8fc378caa990", "fullName": "test_create_order.TestGetOrder#test_get_order_with_bad_courier_id_fail", "labels": [{"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "pc"}, {"name": "thread", "value": "11044-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_create_order"}]}